version: '3.8'

volumes:
  postgres_data:
  static_data:
  nginx_conf:
  
services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: bogdanov2000/yamdb_final
    restart: always
    volumes:
      - static_data:/code/static/
      - nginx_conf:/code/conf.d/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always  
    volumes:
      - static_data:/code/static/
      - nginx_conf:/etc/nginx/conf.d/ 
    ports:
      - "8080:80"  
    depends_on:
      - web    
