version: '3.8'

volumes:
  postgres_data:
  static_data:

services:

  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    volumes:
      - static_data:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    restart: always  
    volumes:
      - static_data:/code/static
    ports:
      - "8000:80"  
    depends_on:
      - web    
