# Generated by Django 3.0.5 on 2020-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200515_2306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=30,
            ),
        ),
    ]
